spring:
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:chupeta
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-ui
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
      jakarta:
        persistence:
          sharedCache:
            mode: NONE  
    show-sql: true
    defer-datasource-initialization: true
    open-in-view: false
    
  output:
      ansi:
        enabled: always
      
name:       PriceTagLookupService

## external DDBB config
ddbbDriver:             "org.h2.Driver"
ddbbUrl:                "jdbc:h2:mem:chupeta"
ddbbUser:               "sa"
ddbbPass:               ""
useStoredProcedure:     false
    
    